"""add_timeline_player_snapshots

Revision ID: 09c1ab2b51a9
Revises: 0d14f65e0526
Create Date: 2026-02-23 01:06:30.117557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09c1ab2b51a9'
down_revision: Union[str, None] = '0d14f65e0526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_player_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=4), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('patient_name', sa.String(length=64), nullable=True),
    sa.Column('soul_color', sa.String(length=1), nullable=True),
    sa.Column('ghost_id', sa.String(length=32), nullable=True),
    sa.Column('ghost_name', sa.String(length=64), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('mp', sa.Integer(), nullable=True),
    sa.Column('mp_max', sa.Integer(), nullable=True),
    sa.Column('cmyk_json', sa.Text(), nullable=True),
    sa.Column('region_id', sa.String(length=32), nullable=True),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('buffs_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_timeline_player_snapshots_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_timeline_player_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_player_snapshots'))
    )
    with op.batch_alter_table('timeline_player_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_game_user', ['game_id', 'user_id'], unique=False)

    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_snapshot_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_players_current_snapshot_id_timeline_player_snapshots'), 'timeline_player_snapshots', ['current_snapshot_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_snapshot_id', sa.String(length=32), nullable=True))
        batch_op.create_index('ix_timeline_snapshot', ['player_snapshot_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_timeline_events_player_snapshot_id_timeline_player_snapshots'), 'timeline_player_snapshots', ['player_snapshot_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_timeline_events_player_snapshot_id_timeline_player_snapshots'), type_='foreignkey')
        batch_op.drop_index('ix_timeline_snapshot')
        batch_op.drop_column('player_snapshot_id')

    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_players_current_snapshot_id_timeline_player_snapshots'), type_='foreignkey')
        batch_op.drop_column('current_snapshot_id')

    with op.batch_alter_table('timeline_player_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_game_user')

    op.drop_table('timeline_player_snapshots')
    # ### end Alembic commands ###
