"""initial_schema

Revision ID: 0d14f65e0526
Revises: 
Create Date: 2026-02-15 04:08:56.149582
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d14f65e0526'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('preparing', 'active', 'paused', 'ended', name='game_status'), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('flags_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_games_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('platform_bindings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_uid', sa.String(length=128), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_platform_bindings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_bindings'))
    )
    with op.batch_alter_table('platform_bindings', schema=None) as batch_op:
        batch_op.create_index('ix_binding_platform', ['platform', 'platform_uid'], unique=True)
        batch_op.create_index('ix_binding_user', ['user_id'], unique=False)

    op.create_table('item_definitions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('effect_json', sa.Text(), nullable=True),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_item_definitions_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_definitions'))
    )
    with op.batch_alter_table('item_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_item_def_game', ['game_id'], unique=False)
        batch_op.create_index('ix_item_def_name', ['game_id', 'name'], unique=False)

    op.create_table('regions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_regions_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index('ix_region_game', ['game_id'], unique=False)
        batch_op.create_index('ix_region_game_code', ['game_id', 'code'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_locations_region_id_regions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_location_region', ['region_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('identity', sa.String(length=128), nullable=True),
    sa.Column('portrait_url', sa.String(length=512), nullable=True),
    sa.Column('soul_color', sa.String(length=1), nullable=False),
    sa.Column('personality_archives_json', sa.Text(), nullable=True),
    sa.Column('ideal_projection', sa.Text(), nullable=True),
    sa.Column('current_region_id', sa.String(length=32), nullable=True),
    sa.Column('current_location_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name=op.f('fk_patients_current_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_region_id'], ['regions.id'], name=op.f('fk_patients_current_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_patients_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patient_game', ['game_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('region_id', sa.String(length=32), nullable=True),
    sa.Column('location_id', sa.String(length=32), nullable=True),
    sa.Column('started_by', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'ended', name='session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_sessions_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_sessions_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_sessions_region_id_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_sessions_started_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_game', ['game_id'], unique=False)

    op.create_table('event_definitions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('expression', sa.String(length=128), nullable=False),
    sa.Column('color_restriction', sa.String(length=1), nullable=True),
    sa.Column('target_roll_total', sa.Integer(), nullable=True),
    sa.Column('target_roll_detail', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_event_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_event_definitions_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_event_definitions_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_definitions'))
    )
    with op.batch_alter_table('event_definitions', schema=None) as batch_op:
        batch_op.create_index('ix_event_def_name', ['session_id', 'name'], unique=False)
        batch_op.create_index('ix_event_def_session', ['session_id'], unique=False)

    op.create_table('game_players',
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('DM', 'PL', name='player_role'), nullable=False),
    sa.Column('active_patient_id', sa.String(length=32), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_patient_id'], ['patients.id'], name=op.f('fk_game_players_active_patient_id_patients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_players_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_players_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'user_id', name=op.f('pk_game_players'))
    )
    op.create_table('ghosts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('current_patient_id', sa.String(length=32), nullable=True),
    sa.Column('origin_patient_id', sa.String(length=32), nullable=True),
    sa.Column('creator_user_id', sa.String(length=32), nullable=True),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('cmyk_json', sa.Text(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('mp', sa.Integer(), nullable=False),
    sa.Column('mp_max', sa.Integer(), nullable=False),
    sa.Column('origin_name', sa.String(length=64), nullable=True),
    sa.Column('origin_identity', sa.String(length=128), nullable=True),
    sa.Column('origin_soul_color', sa.String(length=1), nullable=True),
    sa.Column('origin_ideal_projection', sa.Text(), nullable=True),
    sa.Column('origin_archives_json', sa.Text(), nullable=True),
    sa.Column('archive_unlock_json', sa.Text(), nullable=False),
    sa.Column('origin_name_unlocked', sa.Boolean(), nullable=False),
    sa.Column('origin_identity_unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name=op.f('fk_ghosts_creator_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_patient_id'], ['patients.id'], name=op.f('fk_ghosts_current_patient_id_patients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_ghosts_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_patient_id'], ['patients.id'], name=op.f('fk_ghosts_origin_patient_id_patients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ghosts')),
    sa.UniqueConstraint('current_patient_id', name=op.f('uq_ghosts_current_patient_id')),
    sa.UniqueConstraint('origin_patient_id', name=op.f('uq_ghosts_origin_patient_id'))
    )
    with op.batch_alter_table('ghosts', schema=None) as batch_op:
        batch_op.create_index('ix_ghost_game', ['game_id'], unique=False)

    op.create_table('player_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('item_def_id', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_def_id'], ['item_definitions.id'], name=op.f('fk_player_items_item_def_id_item_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_player_items_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_items'))
    )
    with op.batch_alter_table('player_items', schema=None) as batch_op:
        batch_op.create_index('ix_player_item_patient', ['patient_id'], unique=False)
        batch_op.create_index('ix_player_item_unique', ['patient_id', 'item_def_id'], unique=True)

    op.create_table('session_players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_session_players_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_players_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_players'))
    )
    with op.batch_alter_table('session_players', schema=None) as batch_op:
        batch_op.create_index('ix_session_player_patient', ['patient_id'], unique=False)
        batch_op.create_index('ix_session_player_session', ['session_id'], unique=False)
        batch_op.create_index('ix_session_player_unique', ['session_id', 'patient_id'], unique=True)

    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_timeline_events_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_timeline_events_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index('ix_timeline_game', ['game_id'], unique=False)
        batch_op.create_index('ix_timeline_session_seq', ['session_id', 'seq'], unique=False)

    op.create_table('buffs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ghost_id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('expression', sa.String(length=128), nullable=False),
    sa.Column('buff_type', sa.Enum('numeric', 'dice', 'attribute', 'text', name='buff_type'), nullable=False),
    sa.Column('remaining_rounds', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_buffs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_buffs_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ghost_id'], ['ghosts.id'], name=op.f('fk_buffs_ghost_id_ghosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buffs'))
    )
    with op.batch_alter_table('buffs', schema=None) as batch_op:
        batch_op.create_index('ix_buff_game', ['game_id'], unique=False)
        batch_op.create_index('ix_buff_ghost', ['ghost_id'], unique=False)

    op.create_table('color_fragments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('holder_ghost_id', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_color_fragments_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['holder_ghost_id'], ['ghosts.id'], name=op.f('fk_color_fragments_holder_ghost_id_ghosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_color_fragments'))
    )
    with op.batch_alter_table('color_fragments', schema=None) as batch_op:
        batch_op.create_index('ix_fragment_game', ['game_id'], unique=False)

    op.create_table('print_abilities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ghost_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('ability_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ghost_id'], ['ghosts.id'], name=op.f('fk_print_abilities_ghost_id_ghosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_abilities'))
    )
    op.create_table('communication_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('initiator_patient_id', sa.String(length=32), nullable=False),
    sa.Column('target_patient_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='comm_status'), nullable=False),
    sa.Column('transferred_ability_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_communication_requests_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiator_patient_id'], ['patients.id'], name=op.f('fk_communication_requests_initiator_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_patient_id'], ['patients.id'], name=op.f('fk_communication_requests_target_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transferred_ability_id'], ['print_abilities.id'], name=op.f('fk_communication_requests_transferred_ability_id_print_abilities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_requests'))
    )
    with op.batch_alter_table('communication_requests', schema=None) as batch_op:
        batch_op.create_index('ix_comm_game', ['game_id'], unique=False)
        batch_op.create_index('ix_comm_initiator', ['initiator_patient_id'], unique=False)
        batch_op.create_index('ix_comm_status', ['game_id', 'status'], unique=False)
        batch_op.create_index('ix_comm_target', ['target_patient_id'], unique=False)

    op.create_table('event_ability_usages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_def_id', sa.String(length=32), nullable=False),
    sa.Column('ghost_id', sa.String(length=32), nullable=False),
    sa.Column('ability_id', sa.String(length=32), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['print_abilities.id'], name=op.f('fk_event_ability_usages_ability_id_print_abilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_def_id'], ['event_definitions.id'], name=op.f('fk_event_ability_usages_event_def_id_event_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ghost_id'], ['ghosts.id'], name=op.f('fk_event_ability_usages_ghost_id_ghosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_ability_usages'))
    )
    with op.batch_alter_table('event_ability_usages', schema=None) as batch_op:
        batch_op.create_index('ix_event_usage_event_ghost', ['event_def_id', 'ghost_id'], unique=False)
        batch_op.create_index('ix_event_usage_unique', ['event_def_id', 'ghost_id', 'ability_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_ability_usages', schema=None) as batch_op:
        batch_op.drop_index('ix_event_usage_unique')
        batch_op.drop_index('ix_event_usage_event_ghost')

    op.drop_table('event_ability_usages')
    with op.batch_alter_table('communication_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_comm_target')
        batch_op.drop_index('ix_comm_status')
        batch_op.drop_index('ix_comm_initiator')
        batch_op.drop_index('ix_comm_game')

    op.drop_table('communication_requests')
    op.drop_table('print_abilities')
    with op.batch_alter_table('color_fragments', schema=None) as batch_op:
        batch_op.drop_index('ix_fragment_game')

    op.drop_table('color_fragments')
    with op.batch_alter_table('buffs', schema=None) as batch_op:
        batch_op.drop_index('ix_buff_ghost')
        batch_op.drop_index('ix_buff_game')

    op.drop_table('buffs')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_session_seq')
        batch_op.drop_index('ix_timeline_game')

    op.drop_table('timeline_events')
    with op.batch_alter_table('session_players', schema=None) as batch_op:
        batch_op.drop_index('ix_session_player_unique')
        batch_op.drop_index('ix_session_player_session')
        batch_op.drop_index('ix_session_player_patient')

    op.drop_table('session_players')
    with op.batch_alter_table('player_items', schema=None) as batch_op:
        batch_op.drop_index('ix_player_item_unique')
        batch_op.drop_index('ix_player_item_patient')

    op.drop_table('player_items')
    with op.batch_alter_table('ghosts', schema=None) as batch_op:
        batch_op.drop_index('ix_ghost_game')

    op.drop_table('ghosts')
    op.drop_table('game_players')
    with op.batch_alter_table('event_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_event_def_session')
        batch_op.drop_index('ix_event_def_name')

    op.drop_table('event_definitions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_game')

    op.drop_table('sessions')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_game')

    op.drop_table('patients')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_location_region')

    op.drop_table('locations')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index('ix_region_game_code')
        batch_op.drop_index('ix_region_game')

    op.drop_table('regions')
    with op.batch_alter_table('item_definitions', schema=None) as batch_op:
        batch_op.drop_index('ix_item_def_name')
        batch_op.drop_index('ix_item_def_game')

    op.drop_table('item_definitions')
    with op.batch_alter_table('platform_bindings', schema=None) as batch_op:
        batch_op.drop_index('ix_binding_user')
        batch_op.drop_index('ix_binding_platform')

    op.drop_table('platform_bindings')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
